services:
  frontend:
    build: ./frontend
    networks:
      - traefik-net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bellegosse-frontend.rule=Host(`bellegossedu34.fr`) || Host(`www.bellegossedu34.fr`)"
      - "traefik.http.routers.bellegosse-frontend.entrypoints=websecure"
      - "traefik.http.routers.bellegosse-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.bellegosse-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.bellegosse-frontend-http.rule=Host(`bellegossedu34.fr`) || Host(`www.bellegossedu34.fr`)"
      - "traefik.http.routers.bellegosse-frontend-http.entrypoints=web"
      - "traefik.http.routers.bellegosse-frontend-http.middlewares=redirect-to-https"

  backend:
    build: ./backend
    env_file: .env
    networks:
      - traefik-net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bellegosse-backend.rule=Host(`api.bellegossedu34.fr`)"
      - "traefik.http.routers.bellegosse-backend.entrypoints=websecure"
      - "traefik.http.routers.bellegosse-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.bellegosse-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.bellegosse-backend-http.rule=Host(`api.bellegossedu34.fr`)"
      - "traefik.http.routers.bellegosse-backend-http.entrypoints=web"
      - "traefik.http.routers.bellegosse-backend-http.middlewares=redirect-to-https"

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik-net

volumes:
  db_data:

networks:
  traefik-net:
    external: true
    name: speech-synthesis_app-network